#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <limits.h>

typedef struct HEAP{
    int x;
    int y;
    int x_p;
    int y_p;
    char type;
    int visited;
    int distance;
}HEAP;

typedef struct XY_path{
    int x;
    int y;
    struct XY_path *next;
}XY_path;

#define velx 100
#define vely 100

XY_path *journey = NULL;        //vysledna cesta
HEAP **heap = NULL;         //halda
int big = 0;            //pocet prvkov v halde
HEAP ***tracing = NULL;     //dvoj rozmerne pole  struktur na vytvorenie mapy

/*char map[velx][vely] = {
        {"CHCPC"},
        {"CCCHC"},
        {"HCDCC"},
        {"CHCHP"},
        {"CHCCC"}
*/
char** map;
/*
char map[velx][vely] = {
        {"CCCCHHHCCHCCHHCCCCCCCCPCHHCCCC"},
        {"HCCCGH0CCCHCHCHCHCHCCCHHHHCCCH"},
        {"CHCHCHHCCCHCCHHCCHCHCCCCCCHCCC"},
        {"HHHHCCCCHHCHCCCHHCCCCHCCHCCHHC"},
        {"CCHCCCCHCHCCHHHCCHCCCCCCCCCHCH"},
        {"CCHCCCCHCHHCCCCHCHCHHCCCCCCCHC"},
        {"CCCHCHCHCCHCCHCCCCHCCHHHHHHPHC"},
        {"CCCCCC1HCHCHCCHCCHCHCCCCHHHCCC"},
        {"CHHCHHHHCHHHCCHHC1HHHHHCHHCHHH"},
        {"CHHCCCCCCCHCHHCHCCPCHCCHCHHCHH"},
        {"CHCCCHCCCCHCHHCHCCC0CCCCCCCCHC"},
        {"CCCCHCCHHCCCCCCHHHCCCHCCHCCCHC"},
        {"CHCHCHHCHHHCCHCHHCHHHCCHCHCHCC"},
        {"CCHCCCCHCCCCCCHCCCCHHHCCCHCCHH"},
        {"CCCHHHCCHHCCCCCCHCCHHHHCCH0CCH"},
        {"HHCHHHCCDHHHHCHCCHHCCCC0CHHHCC"},
        {"HHHCCCCCCHCHHHCCC1CCCCCCCCCCHC"},
        {"CCHCHCCCCCHCCCHHCHHCHCCCHHCCCH"},
        {"CCCHHHHCCCCCCHCHCHCCHCCCCCHCCC"},
        {"CHHCHCCCCCHCHCCHHCCHCCCCCCHCHC"},
        {"CCCHHHHCCHCCHCHCHCCHHCCCHHCHHC"},
        {"HHHHCHCCHCHCCHCCCHCCHCHHCCHCCC"},
        {"HHCCCHCHCHHCHCCCCCCCCCCHCCCHCC"},
        {"CCCCCCHHHHHHHCHCCCCHCCCCCCCHHC"},
        {"CCHCHHCCCCCPHHCHCCHCHCCCCHHCHC"},
        {"CCHHHHCCCCCCCCCHCHHCCHCCCHHCHH"},
        {"HHCHCCHHHHCHHHCHHCHCHCHHCHHHHC"},
        {"CCHHCCCCCHHHCCHHCCCHHHCHCCCCCC"},
        {"CHHCCCC0HCHCCHCCHHCCCCCCCHPHCC"},
        {"CCHHCCCHCHCCCCCHCCCHCCHCCCHCCC"}
};
 */


 /*
char map[velx][vely] = {
        {"CHP"},
        {"CCH"},
        {"HCD"}


};

*/

void bubble_up(struct HEAP *new){               //vkladanbie do haldy
    int i =big;
    while (heap[(i - 1) / 2]->distance > heap[i]->distance)  {
        int x = (i - 1) / 2;
        HEAP *temp = heap[x];
        heap[x] = new;
        heap[i] = temp;
        i = (i - 1) / 2;
    }
}

void bubble_down(struct HEAP *new, int i){
    HEAP *temp = NULL;
    if (2*i+2 > big-1)
        return;
    if (2*i+1 > big -1)
        return;
    if (heap[2*i+1]->distance < new->distance || heap[2*i+2]->distance < new->distance){
        //if ( new->distance > heap[2*i+1]->distance || new->distance < heap[2*i+2]->distance ){
        if (heap[2*i+1]->distance<=heap[2*i+2]->distance){
            temp = heap[2*i+1];
            heap[2*i+1] = new;
            heap[i] = temp;
            i = 2*i+1;
            bubble_down(new,i);
        }
        else {
            if (heap[2 * i + 2]->distance < heap[2 * i + 1]->distance) {
                temp = heap[2 * i + 2];
                heap[2 * i + 2] = new;
                heap[i] = temp;
                i = 2 * i + 2;
                bubble_down(new, i);
            }
        }
    }
}

HEAP *get_min() {
    HEAP *temp = NULL;
    if (big>0) {
        big--;
        temp = heap[0];
        heap[0] = heap[big];
        bubble_down(heap[0],0);
        heap = realloc(heap,(big)*sizeof(HEAP));
    }
    return temp;
}

void free_heap(){
    while(big!=0) {
        get_min();
    }
}

void init_visited(int n, int m){                //2 rozmerne pole struktur      ,NAMAPUJEM MAP NA TRACING
    int x,y;
    XY_path *iter = journey;

    if (tracing!= NULL) free(tracing);
    tracing = (HEAP***)malloc(n*sizeof(HEAP**));
    for (x =0;x<n;x++) {
        tracing[x] = (HEAP**)malloc(m*sizeof(HEAP*));
        for (y = 0; y < m; y++) {
            tracing[x][y] = (HEAP *) malloc(sizeof(HEAP));
            tracing[x][y]->x = x;
            tracing[x][y]->y = y;
            tracing[x][y]->x_p = 0;
            tracing[x][y]->y_p = 0;
            tracing[x][y]->type = map[x][y];
            tracing[x][y]->visited = 0;
            tracing[x][y]->distance = INT_MAX;
        }
    }

    while(iter != NULL) {
        tracing[iter->x][iter->y]->type = tracing[iter->x][iter->y]->type+32;                   //zmenim hodnotu charu P,aby mi nenaslo uz najdenu princeznu
        iter = iter->next;
    }
}

int type_of(char type){
    switch (type){
        case 'H': return 2; //hustina
        case 'N': return -1; //nepriechodna cesta
        default: return 1;
    }
}

void insert( int ip, int jp, int distance, HEAP *child) {
    int plus_value = type_of(map[child->x][child->y]);

    if (plus_value == -1)
        return;
    if ( plus_value + distance >= child->distance )
        return;

    heap = realloc(heap,(big+1)*sizeof(HEAP*));
    heap[big] = child;

    heap[big]->distance = distance+plus_value;
    heap[big]->x_p = ip;
    heap[big]->y_p = jp;
    bubble_up(heap[big]);
    big++;
}



void add_neighbours(int x, int y, int n, int m){
    tracing[x][y]->visited = 1;
    if (tracing[x][y]->distance == -1) return;


    if (x>=1 && tracing[x-1][y]->visited != 1) insert(x, y, tracing[x][y]->distance, tracing[x-1][y]);// horny sused
    if (x<n-1 && tracing[x+1][y]->visited != 1) insert(x, y, tracing[x][y]->distance, tracing[x+1][y]);//dolny sused
    if (y>=1 && tracing[x][y-1]->visited != 1) insert(x, y, tracing[x][y]->distance, tracing[x][y-1]);//lavy sused
    if (y<m -1&& tracing[x][y+1]->visited != 1) insert(x, y, tracing[x][y]->distance, tracing[x][y+1]);//pravy sused
}


void add_journey(HEAP *found){
    XY_path *new = (XY_path*)malloc(sizeof(XY_path));
    new->x =found->x;
    new->y =found->y;
    new->next = journey;
    journey =new;
}

XY_path *mergepaths(XY_path *path, XY_path*new_path){           //spajanie ciest
    XY_path *iter = path;

    if (path == NULL) {
        return new_path;
    }
    else {
        while (iter->next != NULL)
            iter = iter->next;
        iter->next = new_path->next;
        return path;
    }
}

XY_path *backtrack(XY_path *path, int startX, int startY ,HEAP *found){     //od draka/princeznej na zaciatok/na povodne suradnice
    HEAP *iter = found;
    XY_path *first = (XY_path *) malloc(sizeof(XY_path));
    first->x = iter->x;
    first->y = iter->y;
    first->next = path;
    path = first;
    do {
        iter =tracing[iter->x_p][iter->y_p];
        XY_path *new = (XY_path*)malloc(sizeof(XY_path));
        new->x = iter->x;
        new->y = iter->y;
        new->next = path;
        path = new;
    }
    while(iter->x != startX || iter->y != startY);
    return path;
}


HEAP *search(int n,int m, char sign, int **x , int **y, XY_path **first, XY_path **mergedpath) {
    init_visited(n,m);
    int i = **x;
    int j = **y;
    tracing[i][j]->distance = 0;
    add_neighbours(i,j,n,m);

    HEAP *iter = NULL;
    do {
        iter = get_min();
        if (iter == NULL)
            break;
        add_neighbours(iter->x,iter->y,n,m);
    } while (iter->type != sign);
    return iter;
}


int *make_array(XY_path *xy_path, int **dlzkacesty){            //vypis cesty finalnej
    int *path = (int*)malloc(sizeof(int));
    XY_path *iter = xy_path;
    int counter = 0;
    while(iter!=NULL){
        counter+=2;
        path = realloc(path,counter*sizeof(int));
        path[counter-2] = iter->y;
        path[counter-1] = iter->x;
        iter = iter->next;
    }
    printf("\n");
    **dlzkacesty = counter/2;
    int lala = 0;
    for (int i = 0; i <counter ; i = i+2) {
        if (map[path[i+1]][path[i]] == 'D') {
            printf("DRAK ");
            lala = 1;
        }
        if (map[path[i+1]][path[i]] == 'P' && lala == 1)
            printf("PRINCEZNA ");

        printf("[%d,%d]%c\n",path[i],path[i+1], map[path[i+1]][path[i]]);
    }
    return path;
}

int* zachran_princezne(char **kingdom, int n, int m, int t, int *dlzka_cesty) {
    //map = kingdom;
    int i,j,P=0,type,z=0,q=0,*x= &z,*y= &q;
    for( i=0;i<n;i++){
        for( j=0; j<m;j++){
            if(map[i][j] == 'P') P++;           //zistijem princezne,pocet
            type = map[i][j] - 48;
        }
    }

    XY_path *first = NULL;
    XY_path *mergedpath = NULL;

    HEAP *found = search(n,m,'D',&x,&y,&first,&mergedpath);
    add_journey(found);
    mergedpath = mergepaths(mergedpath,backtrack(first,*x,*y,found));
    free_heap();
    for (i = 0;i<P;i++) {
        x = &found->x;
        y = &found->y;
        found = search(n,m,'P',&x,&y,&first, &mergedpath);
        add_journey(found);
        mergedpath = mergepaths(mergedpath,backtrack(first,*x,*y,found));
        free_heap();
    }
    int *path = make_array(mergedpath,&dlzka_cesty);
    return path;
}

int main() {
    int lenght = 0;
    int *LENGHT = &lenght;
    char **kingdom = NULL;

    char ** mapa = (char**) malloc(sizeof(char*)*100);

    mapa[0] = "HCNCNCCHCCHCCHHCHCHHHCCCHCNCHHHCNCCCHCCCCHCCCCCHHCCHCCCCHCCCCCCCCCHCHCCNHCCHCHCHCHCCCCCCCCCCCCCCHCCC";
    mapa[1] = "HHCCNHHHCCHHHHNCCCHCCCCCHHNHCNNHCCCHHCHHCCCCHNHNHCHCHCCHCCHHCHCCCHCHCHHHCCHHHCCCCCCCCNCHCHHCHCHHCCCC";
    mapa[2] = "CHHCHHCCCCHCCCHCNCHCCCHCCHCHCCHHHCHHCHHCCCCHCHCHCCHCCCHCCCHCCCHCCHHHCHHHCCCCCCHCHHCCCCCHCHHCCCCCCHCC";
    mapa[3] = "CHHHHHCHHHCHNCCCHHHCCHCHHCNCCCCCHHCCCCCCHHCCCCCCHCCCHCHCHHCHHCHCCCCCCCCCHNCHCCHHHCCCHNCHCCHCCCHCHCHH";
    mapa[4] = "CCCHHHCHCHCCCHHHHCCHCCHHHHCCCCHHCHCCCHCHHHHHHHCCCCCHHCHCCCCCHCCCCCCHCCCHCCHHHHHCHHHCCCHHHCCCHCCCCCHH";
    mapa[5] = "CCCCNCHCNCCHNCHCCHNHCHCCHHCNHCCCCCHHCCHHHCHHHCCCHNCCHCHCCHCCHHCHCNHCHHCHCCHHCCHHCHCHHCCCHHHCHCHHHCCN";
    mapa[6] = "CCHCCHCHHHCHCHHCNCHCHHHHCCCHCHCNCHHCCCCHHCCCCCCCCCCHHCHCCCHCHCCHHCHCCHCCHHHHCCCCHCNCHCHCCCCCHHHHHCCH";
    mapa[7] = "CHCHHCCCHCCCCCCHCHCHCCHHHHCCHHCCCHCHHCHCCCHCHCHHHCNHCCCCHCHHCHHCCHCCHCCCHHHCHHCCCCNCCCCHCHCCNCCHCHHC";
    mapa[8] = "CHNCCHCCCCHCNHHHHHHCCCCHCHHCHHCHCCCCCCCCHHCCHCCHCHHHCCHCCHNCCCCCNHNCHHCCCHCCNHHHHCCCCHCCCHCHHNHCHCCH";
    mapa[9] = "CHCCCCCCHHHNHCCCCCNCCCCCCHCHCCCCCHCCCHHHCHHHNCHHHCCHHHHHHHCHHHCHHCCCCCNHCHCCCHCHCCHCHHCNHCHCHCHHCCCC";
    mapa[10] = "CCCHHCHHCCCCHCHHHCCCCHHCCCCCCCHCCCHHCHHCCCCCCHCCCCHCHHCCCCNNHCNCHCCCCHHCHCCCHNHCHHCCHHCCNHHCCHCCCCHH";
    mapa[11] = "HNNNHCCCHHCCCCCHHHHCCHHHHCHHHHHHHCCCCCCCCHCHHCCCHCCHCNCHHCHCHHCCHCNCHCHHNCHHHCHCHHCHHHHCCCHHCHHCHNNC";
    mapa[12] = "CCCCCCHHHCHCCHHCHCCHCHCHHCHCCCCCHCCCCCHCHCHHHCCCHCCHHCCCCCHCCHHHHCHCCCHHCCHCCCHCCNHHCCNCCCHHCCCCHCHC";
    mapa[13] = "CCHHHHCNNHCHHHCCCCNCHCHHCHCCNHHCCCCHHCNHHCHCHCHCCHCCCHHHHCCHCCHHCHHCHCCHHCCCCHCHCNCHNHCCCNHCCHHCCCCH";
    mapa[14] = "HCCCHHCHCCCCCCHCHCCHCNHHHCCNHHHHCCCCHCCCHHHCCHHHCHCNCCCCHCHCCCCHHCHCCCCCCCCCCHCHHHCCCCHHCCCHHCCCHCHN";
    mapa[15] = "HCHCCCHNHHHHNNCHCCHCCHCCNCHCCCHCHCHHHCHHCHCHNHCCHCHHCCHCCHCCCNHCHCHCNNCCNHCHHCHNHCHHNHCHHHCHHHHHCNCC";
    mapa[16] = "HHHCCHCCCCCHCCHHHHCCHCCHNHHHCCHCHCCHCCHCHCHHCHCCHCCCCCCCCCCNHCCCHHHCHHHCCHCNCCCCHHCCCHHHCCCCHCCCHHHH";
    mapa[17] = "CCHNHCCCCHHHHNCCCHNCCCCCCHHCHHHHCHCCNCCHCCHNCCCHCCHCCCCCCHCCHHCCCHHNCHCCCCHHHHCCCCCCCHHHCCHCCHHHCHNH";
    mapa[18] = "HCCHHHHHHHCHCHCCCCCHCHHHCCCCCHHHCHHCHCCCHCHHCCCCHNCHCHCCCHCHHCCCCCCHCHCHCCCCCCHNCCCCCHCHHCCCHCCCCHCH";
    mapa[19] = "CCCHCCNCHHCCHHCHCCHHCCCHCCHCCHCHCCCCHHCCCCCCHHHCHHHHCHHHCCNCCCCHCHHHHCHCCCCCCHHHHCHHCHHHCCHHCCHCCHCC";
    mapa[20] = "CCCHHCHCCCHCCCHCCHCHHHNCHHHCHCCCCCCHCCCHHCHCCCCCCCCCHCCHCHNHHCHNHCNNCCHCCHCHCCCCHCNCHCNCCCCHCHCCCCCH";
    mapa[21] = "HHCHCHCHCCHCCHCCNCNHCHCCHHCHHCHCCCCCHCHCCCCCHHNHHCCCHHHHCHHHHCCHCCCCHCCHCNCCHNCCHCHHHNHCCHCCCCCCHCHH";
    mapa[22] = "HCCCCCCCHCHCCHHNHCCCCCCCCHCHHCNCCNCHHCHHHHCHHCHCCCCHHCHHHHHCCCHCHHHCHCNHCCCCCHCHCCCHHCHHHCHHCCCCCNCH";
    mapa[23] = "CHNCHHCCHCHCHHHHHCCCCHCCHCCCCCHCCHCCHCCCCCHHCHHNHNHHCCHHCHCCCCCHHHCHCCHCCCCCCHCCHHHHCCHCNHCCHCCCCHCH";
    mapa[24] = "HCCCCCHCCCHCCCCHHHHCCCHCCHCHHCNHCCHCCCCHHCHNHCHHNCHHHCCHCHCCCHCCHCHCHHCCCHNCHHHCHHCHCHCNHCCCHCCHCHCH";
    mapa[25] = "HCCCCCCNCHCHNHCHCHHCHCHCHCCCCCHNCCCCNCCCCHHCHCHCCCCCHCCHHHCNNHCHHCCCCCNHCCCHHCHHHCCHHCHCCHHCCNCCCNCC";
    mapa[26] = "CHCHCCHHHCCCHCCCCCCCCCCHHCCCCNHCHCCHCCCCCNCCCCCCHCCCCCCCHCCHCCHCHCHHHCCCHCHHNCCHHCHCCHHCCHCHNCCHCHCC";
    mapa[27] = "HCCHCNCCHHCCHCCCHCCHCHHHHNCCCHCHCCCCCCHNCCHNCHHCCHHCNCHCCHHHHCCHHHCCCHCCCHCHHCNCNHCHCHCCCHCHHHCCHHCC";
    mapa[28] = "HCHCCCCHHCHHCCCCCCCNHCCCHHCCCCCCCHCHHHCCHCCHCCCCHCCHHHCCNCHHCHCHHHHCHHHHCCCCHHHHCHCHHHHHCCHNCCCCHHCH";
    mapa[29] = "HHCNCHHHHCCHCCCHHHCHCCCCCHHCCCCHCCHCHNHCHCHCHHCHCHCCHHCCHCHCCHCHCHCCCCCCCCHCCHCHCHHHCCHHCCHCHHCCHHCH";
    mapa[30] = "CCCCHHHCCCCCCHCHCCHHCCHHCHCCCCHCCCCCHHCHCCCHCCHCHHHCHHCCHCHHCCCCHCHCHNCNCCCHCHHHHHHCHHCNNCHHHCHCHHCH";
    mapa[31] = "HHCHCHCHCCCHCCNCCHCHHCCCCHHHHCHHHCHCNCHCCCHCHCCCCHCCCCCCCHCHHCHHHCCHHCHCHHHHCCCCCCHNCCHHHHCCHCCHCNHH";
    mapa[32] = "HCCCCHHHCCHCHCCCHHCCHHHCCCCHHHCCHCHHCCCCCHHCHHCCHCCHHHNCCHHCCHCHHHCHHCHHCCCHHCCCHHCHCCCHCHCCCCCHCCCC";
    mapa[33] = "CHHHHNCHCCCCCHCHCHHCCCCHHCCCHCNCNCNHCCHCHHCCCNHCCHCHHHCHCCCHNNHCNNCHCCCHCHCCCNCCHCHHHNCCCHCCHCCHCCCH";
    mapa[34] = "CCCHCCCCHCHCHCHHCCCHHCHHHHCCHCHHHCCCHCCCCCCHHHCHCCHHCCHCHCHCHHHHHCCCCCCHNHHCCNHCHCHHHCCHHCCCCHCHCHCH";
    mapa[35] = "NHCCHCCCCHHHHHNNCHHCCHCHCCCHCCCCHCHCCHCCHCHHCNHCHCCCHHCHCCCCCHCCHCHCHHHHCCCCHCHCCHCHHCCCHHCHCHHCCCHN";
    mapa[36] = "HNHHCHCCCCCCCHHCHCCCCHHHCNCHHHCCHCHCHCHCCHHCCCHNHCCCCCNHCHCCHNHHHCHHHHCHCHCCCCCHCNHHCNHHHHCHHHHCCCCH";
    mapa[37] = "HHCCCCHNCCHHHCCCCHCHHHHCCCHCCCCHHCHCCHHHCCNCNHHHHHHHCCHCCHHHHCCHHCCHHHHCHCHHCHHHCHHHNHHHNCCCHHCCCHCC";
    mapa[38] = "HHHHHCCNHNCCCCCCHHHHHHCHHCNCCCHCHHHCCCHCHCCNCCCHCCHHCCCCHCCCHCCHHCCNCCCCHCCCHCCHCHCCCHCHCCHNCHCCHCCN";
    mapa[39] = "CHCCCHCCHCHCHHCHCCCHCCCHCCHCCHCHCHCHCHHCCHHCCCHCHHCCCCCHCCHCCHHHCHCCCCCCHHHHCHHCCCCCCHCCHHCHCHCCCCNH";
    mapa[40] = "CCHHCCCCHCCCCCCHHCCHCNCHCCCHCNCCCCNCHHCHCCHCCCCNHHCCHCCCCCCHCNNHHCCCCHCHCCCHHHCCHHCCNHHHCCNHCHCHCCCC";
    mapa[41] = "CHHCHHCNCHHHCNHHHHCCCHHHCHCCHCCHHCCHHHNCHCCCHCHCCHCCHCNHHHHHCCNHHCHCCHHHCHCHCCCCHHHCCCCHHCHCHCCCCCHH";
    mapa[42] = "CHHHNCCNHHCCCCCHHCNCCCCHHCHCCCCCHCHHHHCHHHHCCHHCCNCCCCHHCHHHCCHHHCCCCCCCHCCCHCCCHCHCNCCHHCHHHCHHCHHH";
    mapa[43] = "CHCHHCCCCHCCCCCCHCHHCCCHCHHHCCHHCCCCCHCHCCCCHNCHHHHHCHCCCHCHCCHNCCCCHCCHHCHCCCCCCHCHCCHHCCHCHHCCHCCH";
    mapa[44] = "HHCCHCCCCCHHHNHHCCCCCHCCHHHHHCCHHCCCCHCHCCHHHCCHCCHHCCHHCCCCHHCHHCHCCHHCCCCHCCHCCHHCCHHHHCHCNNCHCCCN";
    mapa[45] = "HCCHCCHCHHCCHNCHHHCNCHHHCCCCHCCCCHHHHCHHCHCHCHCCCHHCNHHHHCNCHCCCHCCCHCCCHCCCHCHHHHCCCHCHCHCCHCCHHCCH";
    mapa[46] = "HCHCCCHCCHHNCHCHCCCCCHCCNNCCHHCCHHCCHNHCCCCCHCHCCNCCHCCHHCCCCCHHCHHHCCCCCHHHHCCCHCHCHNCHHCHCCCHHCCHC";
    mapa[47] = "HCNHHCHHCCHCHNCCHCHHHHHCCHHCCHCHHCCHHCCCCHHCHCCCHCCHHCCHHCCNHHNCHCCHHCNCCCHCCHCCHHHCCCCHCCHCCCNHCHCN";
    mapa[48] = "CHHCCHCCHHHCHCCCCCCNHCHCHHCCHCCCHCHCCCCCCHHHCCCCCCCCCNCHCHCHHCHCCHHHCCHCHHCHHHCCCHCHHHHCNCCHCCHCCHCC";
    mapa[49] = "CCCHCNHHCCCHCCCHCHHCHCCCCHCHHHCCHHHCHCCCCHCHCCCHCCHHNCHCCCHNCCHNHHHCHNHCCCCCNCCCHCCCHNHCHCCHCCHCCCHC";
    mapa[50] = "CCHHCNCCCCHCHNHCHCCHHHCCCHHCCHCCHHCCHCHNCCHCCHCHHHCCCNHCHCHHCHCHCNCHCNCHCHHHCCHCNCCCCCHCHCHHCHCCCHHH";
    mapa[51] = "HHCCCNHCHHHCHCHCHHHHCCHCHHCNHHCNHHHCCCCCHCHCCHHCCHCCCHHCCCCCHHCHCHHHHHHHCCHHHCCCCNHCCHCCCHCCCCHCNCHH";
    mapa[52] = "HHCCCCHHCHHHCCNCCHCCCCCNCCHCHCCCCHCHHCHCHHCHCHHCHCNCCCCHHCHNCCCCCHCCHCCHHCHCHCHNHHHHCHCCCCHNHHCCHCHH";
    mapa[53] = "HCHCHHCCCHHCCHCHHNCCHCCHHCHHCCHCCHCCHCCCHCCCCHHCCNHCHCHHHHCCCCCHCCHCHNCCHHCCHHNHCHCHCHHCCHHCCHHHNCCC";
    mapa[54] = "NCCCCHCCHCCHCHHCCHCCCHCHHNCCHCCCHCCCHCCHCCCHCHCCCCCHCHHCHHCHHCHCCHHCNHHCCHCCHHHHCCHHCHCCCCCCHHHCHCCC";
    mapa[55] = "CCCCCCCCHCNNHCHCCNCCHHHHCCCCHNNHCCHCHHCCCCHCNCCCHCCHHHHCCCHCCCCCCHHCHCNNCCHHCHCCCCHCHHCCHCHCHCCCCNCH";
    mapa[56] = "HCHCHCHCHCCHCCCHHHCCCHCHCHCNCCCCHHHCNHCCCCCCCCCHCHHCHCHCCCHHCCCHHCCHHCHCHHHCCCCHCCCHCCCCCHCCCCCHHCCH";
    mapa[57] = "CCCCCHHCNNNCCCHHNCHCCHCHCHHCCHHCHHCHCHHHCNHHCHNNHCHHCCCHHHCCCCCPNCCHCHCCHCCCCCHHCNCCHHCCCCCCCHNCCHHH";
    mapa[58] = "CHCHCHCCCNHCCHHCCCCCCNHHCCHCCHNCHHCCCCCHHCCHHHCHCHCHHCHCHCCCCCCCCHCCCCCHHCCCCNCHHCHCHCCCHCCCCHCHHCHH";
    mapa[59] = "CHNCHCHCCCCCCHCCHCCNCHCCHCHCHHHCHCCHCHCHCHCHCCCCHCCCHHCCCCHHHCHHCCHHCCHHHHCCCNHCHHHHCCCHCCCCCCHHCHHC";
    mapa[60] = "CNCHHHCCCCHHCHHCCHCCNHCHHCHHHCCHCCHCHCHHHCCCCCCHCCHCHCHCHHHCHCCCCHHCCCCCHHHCCHCCHNHHCHCHCHHCHHNHCCCC";
    mapa[61] = "CHCCHHCCCCCHHCCHCCCCHHNHCCCHHCHHCCCCCHCCHCHCCHCCCNHHCCHHCCHHHHHCNCCCCCHCNHCCCHCCHCNCHHCHCCCCCHHCHCCH";
    mapa[62] = "CCNCHCCCNCCCHHCCHCCCCCHHCCHHHCCCHHCHHCHHHHCCCNHCHNHCCHCCCPNCCNCHHCCHHCHCCHCHHCCHCHHHCNCCHHCHNNCCHHCH";
    mapa[63] = "HHCHCHHCHCCCHCCNCCCCCCNCHCCHHCCHCHCCCHNCHCCCHCCHHHCHCHCCHNCHHHCCNHHCHCCCHHCCCCCHHHNHCCCHHCCHCHHCCHNC";
    mapa[64] = "CCCHHHHCCCCCCCHCCCHCHCHCHHHCNHHCHCHHCHCHCHCHCCHCHCCCHCCCCHHHHHHHHNNHCHCCHHCCCCHCCHCCHHHCCCHCHHHHHCCC";
    mapa[65] = "HCCCCNNCCNHCHHCCHCCCCHHCCCHCCHHHNHHHHCCHHHHHCHCHHCHCCCHCHHCHCNCCCCCCCCCHCCHHHCHHCHNCCHCCCHCHCHHCHHCH";
    mapa[66] = "HNCHHCHCCCCHCCHCCHCCHHHCHCHCCHHCCHCCCCHHCHCHHHCHHCCCCCHHCHCHCCHCHCCCCCHHHHCCCHCCCHCCCHCCCCHHHHCHHCHC";
    mapa[67] = "CCHCHHNHHCCHCHCHCCCCCHCCHCCHCCCCHCCHCHCCHCCCCHCCHCHHHCCCHNCCCHCCHCCCCHCCCCHCCCCCHHCCCCHCHCHHCHCCHHHH";
    mapa[68] = "HCHCNHCCCHCHCHHHNCNHCCCNNCCHCCHHCCCCCHHCCCHHHCCCCHCCHCCCHCCHCHHCCCCCHCHHHCCCCHCHNHHHCCCNHCHHHCCCCCCC";
    mapa[69] = "CCCCCCCHCCHNNHNHCCCCCCCHCHNCCCHHHCCHHCCCCCCCHNHCHCHNCCCCCHCCHCHNCHHCCHCCCHCCHCCCNCCCCCCHCHHCCHCHCCCC";
    mapa[70] = "CCHCCCCCHNHCCCCHCHHCHCCNCCHCCCCHHCPHCHHCHCCCHHHCCHCHCCCHCCHHCCHCNCCCHHCHCHCHCCCHHCHHHCHCCHHHCCCCHNCH";
    mapa[71] = "CHCCHHNHHHCHCHHHCCHCCHCCCCHHHHCCHCCHCHCCNHCCCHCHNHNHCHCHHHHCCHHCCCHHHHCCCCCNHHCHCHHHCCHHHCHHCHHHCCCC";
    mapa[72] = "CHHCCCCHNHCCCNHCHCNHHCHHHHHNCCHCNHHHCCCHHHHHCHCHCCNCHHCHHHCHHCCCHCHCHCCCCHHHCHHCHCHHHHCHNCHCCCHCHCCH";
    mapa[73] = "CHNCCHCHHHHCCCHCCHHCCCHHHCHHCCHHCHHCHHNCCCCCCCHCCHHNCHHCCCCCCNHHHHNCHHHHCCCCHNHCHCNCCCCCCCCCHHCCHHNC";
    mapa[74] = "HHCHHCCHCHCHCHCCHCHCCHHCHCHHCHCCHCCCHHHCCHCCCCHCHNHCCHHCCHHCCCHCCCCCCCHCHNCNCCCHCCCHCCHHHHHCCCHHCCHC";
    mapa[75] = "CCHNCCHCCHCNCCCNCCHHNCCNCHHNCHHHCHHCHNHCHCCCCHCHNCHCCHCHHCCCCNCCCCCHHCHHNNHCHCCHHCHCCCCHHHCCCCCCHCCC";
    mapa[76] = "CCHCCCHHHHNCHHCHCCCHHCHHCCCHHCHCHHCCHCHCHHHCHHCCCHCCCCHCNCCCHCHHCCHCNCCCHCCCCCHHHNCHHHHCCHCHCCHCCCCH";
    mapa[77] = "HCCCCHCHCCCCCCNCHNHCHCCCCHCCCCCHHHHHCHCCHCCCCHHHCCHCHHHCHHHCCCCHHCHCHHCCCCCNCCCHHCNCCHCHCCCHCCHCCCHC";
    mapa[78] = "CHCHHNHCCHCHCCCHCHCHCHCHHHHCHHNHCCCHCHCCCCCHCHHCCCCCHHHCCCCCCHNCCCHHHHHHCCCCHHHHHCHCCCCHHHHCHCCCCHHC";
    mapa[79] = "CCCCCCCCCCCHHHHCHCCHCCHCHCHCCCHHCCCHCCCCCNHCHCHHCHCCCCCCHNCHCHNHCCCCHHHCCCCHCHCHCCCCCCCCCCHHHCCHHCHC";
    mapa[80] = "NHCCHHHCHHCCCCCCCCCCHCHCCHCHCCCCCHCCCCHCCCCCHCCCNCCCHHCHCCHCHHCCCHCHCCCHNHHHHHHNHHHHHHCHHCCHHCCCCHCH";
    mapa[81] = "HCCCCHCHHHCCCCCCCNCCCHHHHHHCHCCHCNHCHCCHCCHHCHCCCHCHCCHHHHNHCCCNHHHNCCNHHHCNCNNHCCCCNCCHCCHCHHHCHCHH";
    mapa[82] = "HHHCCHHCHHCCNHHHHHCCCCCCHCCHCCHCCHCCCCHCCCCHCHCCHCCCHCCCHCCCHHCCHCHNHCCHCCCHNCCHHHCCHHCHNHHHCCHCCCHC";
    mapa[83] = "HHHHCCCCHHHCCCNHCCCHHCCCNCCHCCCCNHHCCCCHHCCCCCCHCCHCCNCHCCCHCCCCCCCCCCCHCHHHHHCHCCHHCHCCCCCHCCHCHCHC";
    mapa[84] = "HHHNCCHHCCHHHNCCCHHCCCCCCCHCCCHCHNCCHHHCCHHCCHHHHCHCCHHHCCCHHHCHHCCHCNCHCCHHCNHCCNHHHCCCCCCCCHHCCHHC";
    mapa[85] = "CCHHCCCHCCCCNCHCHCCHCHCHCNCHCCHCCCCCHHHCCHCHCCHHCCCHCCCPHCCCHHCHHHCHCCCCNCCCHHNCCNCCCCCNHCHCHHHHHHCC";
    mapa[86] = "HHHHHHCNCHHCCHCCCHCCCCCCCCCHCHNCHCCCCHHHHHCCCHCCCCCCCHHCHCCHHCHCCHHCHHHCHCCNHCCCCHCCCCHCHCCHCCCHHHHC";
    mapa[87] = "CCHCHHHCNHHHCCHCCCCCNCCNHCCCCCCCHCCCCCNNCCHCHHNCCCCCNHHCNCCHHHCHCHCHCCCCHHCHHHHCCHNCHHHHHHCHCCHHHHCC";
    mapa[88] = "CCCHHCHCHCHCCCCCCHHCHHHCCCCHHHHCCCNHCHCCCCCCHCHHCCNCCCHHCCCCCHCCHHCHNCHCHCHCHCCCCHHCHCCHHCCCCCHCHHHH";
    mapa[89] = "HCCHCCHHCHCCHCHCCHHHCCCHCCHHHCHHCCCCCCHCCHCHHHCCNCCCCCNCCCHCHCHCCHCNCCCHCHHCCCCCHHCHCCCHHCHCHCCHCCCH";
    mapa[90] = "CCCHHCHCHCCCCCCCCCCCHCHCHCCCHCHHHHHCCCHHHHHNHHCHCHCCHCCHCHCHHCCCCCCHCCHCNCNCHCCHCHHCHHHHHCCCHHCCCCCH";
    mapa[91] = "HCHCCHHCHCNCCHCCCCHCCHCCCHHHCCCCHNCHHHHHHCHCHHCHHCCHNHCHCCHHHHCCCHCCHHCHHCHHCHCHCHCNCCCCHHCCHCCHHHCC";
    mapa[92] = "CCCCCNCCCCHHCCCCCHHHCHCHCCCHCHHCCCHCCCCCHNCNCHHHCHCHHCHCHCHNCHCHHNHNCCHHHCCHCHNHCCNHCCCHHHCCHNCHHHHN";
    mapa[93] = "HHCCCCCNHHHHHHCNHCHCCCCCHHCCHNHHCHHHHNCHHHHCCCHCCCHCCCCCCCCPHCCHHCHCCHCHCHCCHCCHCCCHHHCCCHCCCCHHCHCC";
    mapa[94] = "HCHCCCHCCCCCHHCCHCCHHCCCHHCCCCCCHHCCCCCHHHCCCCCCCCCCCHCCNHCCHCCHCCCHCHCHCCCCHCCCCCCCHCCHHCCHHCHCHCCC";
    mapa[95] = "CCCCHCHCCHCCHCCCCHCHCCCHCNCCHCHHHCCHCHCHCCCHCHCHCCCHCNHHCCCHHHCHCCNHCHCHCCHCCHHCCCCCCCCCHCHCCCHHCCCN";
    mapa[96] = "CCCCHCCHCHHDCCHCCHCCCCCHHHCHCHHCHCCHCCCCHCCCCCCHCHHCHHCCHCHHCHHCCHHHHCCCCHCHHCCCHCHHCCHCCHCCHHCHHCCH";
    mapa[97] = "CCCCHCCCCHHCHCNHCNCHHCCHCCHHCCNCCCCCCCHCHCCCHCHHCCCCCHHCCCCCCHHCCCCNCHHCCCCHHHCCNCHHCCHCCNCCCCHCHHHH";
    mapa[98] = "CCCCCCCHCCHCHCCCCCHCCHNCCHCCHHCCHHCHHHHCHNCHCNCCCHCCCHHHCHNCHCCHHHCCCCNHCHHCHCCCCCCHCHCCHCCHHCHCCCCC";
    mapa[99] = "CCHCCCNHHHHNCCCCCCHCHCCNHHCCHHCCCCCHCCCHCHCHCHHCHHHCCCHCCHCCCHCHHHNHCHCHHHHCCCCCCHHCCHHHCCCHHCHCCCNN";

    map= mapa;
    int *path = zachran_princezne(kingdom, velx, vely, 50, LENGHT);

    return 0;
}
